# Configuración de Postgres con Docker
version: '3.3' # versión del esquema de docker-compose

services:
  postgres:  #nombre del servicio, postgres
    image: postgres:13 #versión de postgres utilizada
    container_name: my_postgres
    environment: # variables de ambiente
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my_storeDB
    ports:
      - "5432:5432" # Puerto en el que correrá la Base de Datos
    volumes: # para tener persistencia de datos. La carpeta postgres_data se debe añadir a .gitignore
      - postgres_data:/var/lib/postgresql/data

  pgadmin: # nombre de servicio, pgadmin
    image: dpage/pgadmin4 #versión de pgamin quw será descargada
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80 #pgAdmin correrá en el puerto 5050 y se comunicará internamente por el puerto 80 del contenedor

volumes:
  postgres_data:

